#$ -S /bin/bash
#$ -N lorenz
#$ -q all.q
#$ -t 1-3
#$ -cwd


echo -e "-0.1\n0.0\n0.1" >xvals

# create the three lorenz scripts based on template
count=0
for val in $(cat xvals)
do
 let count+=1
 sed "s/x=/x=$val/" ./lorenz_x.py >./lorenz_${count}.py
 sed -i "s/xf_n/xf_$count/" ./lorenz_${count}.py
done

# run the three scripts on individual cores
~/anaconda3/bin/python ./lorenz_$SGE_TASK_ID.py

exit 0
